### ISSUE TITLE
python not a deb package in Ubuntu 22.0

### ISSUE THREAD

**Issue by kinostl** [piku/piku-bootstrap#4]
Ubuntu 22 only comes with python3 and now has a symlink package python-is-python3 and requires explicitely using python2 or python3. 

This can be fixed by changing the piku.yml file to something like this. It might also be possible to just remove the python dependency? I'm not sure about the internals but everything looks python3 so I assume the symlink is safe enough.

```yml
    - name: Install Debian Packages
      apt:
        pkg: ['bc', 'git', 'build-essential', 'libpcre3-dev', 'zlib1g-dev', 'python-is-python3', 'python3', 'python3-pip', 'python3-click', 'python3-dev', 'python3-virtualenv', 'python3-setuptools', 'nginx', 'acl', 'uwsgi-core', 'uwsgi-plugin-python3', 'nodeenv']
        update_cache: true
        state: present
```
